# Generated by Django 5.2 on 2025-05-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        help_text="Укажите тему письма",
                        max_length=100,
                        verbose_name="Тема письма",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Заполните тело письма",
                        null=True,
                        verbose_name="Тело письма",
                    ),
                ),
            ],
            options={
                "verbose_name": "Письмо",
                "verbose_name_plural": "Письма",
            },
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        help_text="Введите email получателя",
                        max_length=100,
                        unique=True,
                        verbose_name="Email получателя",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Введите ФИО получателя",
                        max_length=100,
                        verbose_name="ФИО получателя",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Укажите комментарий",
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
            ],
            options={
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
    ]
