# Generated by Django 5.2 on 2025-05-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(blank=True, null=True, verbose_name="Тело письма"),
        ),
        migrations.AlterField(
            model_name="message",
            name="theme",
            field=models.CharField(max_length=100, verbose_name="Тема письма"),
        ),
        migrations.AlterField(
            model_name="recipient",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Комментарий"),
        ),
        migrations.AlterField(
            model_name="recipient",
            name="email",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Email получателя"
            ),
        ),
        migrations.AlterField(
            model_name="recipient",
            name="full_name",
            field=models.CharField(max_length=100, verbose_name="ФИО получателя"),
        ),
    ]
