# Generated by Django 5.2 on 2025-05-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_dispatch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispatch",
            name="first_sending_datetime",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата и время первой отправки"
            ),
        ),
    ]
