# Generated by Django 5.2 on 2025-05-04 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0004_alter_dispatch_first_sending_datetime"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dispatch",
            old_name="recipients",
            new_name="recipient",
        ),
    ]
