# Generated by Django 5.2 on 2025-05-04 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0005_rename_recipients_dispatch_recipient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispatch",
            name="message",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mailing.message",
                verbose_name="Сообщение",
            ),
        ),
    ]
