# Generated by Django 4.2.2 on 2025-05-09 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0008_dispatch_owner_message_owner_recipient_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dispatch",
            options={
                "ordering": ["status", "end_of_sending_datetime"],
                "permissions": [("can_view_all_dispatches", "Can view all dispatches")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [("can_view_all_messages", "Can view all messages")],
                "verbose_name": "Письмо",
                "verbose_name_plural": "Письма",
            },
        ),
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "permissions": [("can_view_all_recipients", "Can view all recipients")],
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
    ]
