# Generated by Django 4.2.2 on 2025-05-10 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0009_alter_dispatch_options_alter_message_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dispatch",
            options={
                "ordering": ["status", "end_of_sending_datetime"],
                "permissions": [
                    ("can_view_all_dispatches", "Can view all dispatches"),
                    ("can_view_dispatch_detail", "Can view dispatch detail"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [
                    ("can_view_all_messages", "Can view all messages"),
                    ("can_view_message_detail", "Can view message detail"),
                ],
                "verbose_name": "Письмо",
                "verbose_name_plural": "Письма",
            },
        ),
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "permissions": [
                    ("can_view_all_recipients", "Can view all recipients"),
                    ("can_view_recipient_detail", "Can view recipient detail"),
                ],
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
    ]
