# Generated by Django 4.2.2 on 2025-05-11 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0010_alter_dispatch_options_alter_message_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailingattempt",
            options={
                "permissions": [
                    ("can_view_all_mailing_attempts", "Can view all mailing attempts")
                ],
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылок",
            },
        ),
    ]
